# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ahmet/Desktop/test_code/test_code.cache/wt [current_project]
set_property parent.project_path C:/Users/ahmet/Desktop/test_code/test_code.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/ahmet/Desktop/PID_Controller.pkg [current_project]
set_property ip_output_repo c:/Users/ahmet/Desktop/test_code/test_code.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.dcp]
add_files -quiet C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/PID_controller_0.dcp
set_property used_in_implementation false [get_files C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/PID_controller_0.dcp]
add_files -quiet C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/vio_0/vio_0.dcp
set_property used_in_implementation false [get_files C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/vio_0/vio_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/new/duty_cycle_cal.vhd
  C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/new/pwm.vhd
  C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/new/pwm_gen_top.vhd
  C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/new/top_module.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ahmet/Desktop/test_code/test_code.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/ahmet/Desktop/test_code/test_code.srcs/constrs_1/new/constraints.xdc]


synth_design -top top_top_module -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef top_top_module.dcp

catch { report_utilization -file top_top_module_utilization_synth.rpt -pb top_top_module_utilization_synth.pb }
