# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/PID_controller_0.xci
# IP: The module: 'PID_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_4/mult_gen_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_4 || ORIG_REF_NAME==mult_gen_4}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_2/mult_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_2 || ORIG_REF_NAME==mult_gen_2}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_3/mult_gen_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_3 || ORIG_REF_NAME==mult_gen_3}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_5/mult_gen_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_5 || ORIG_REF_NAME==mult_gen_5}]

# XDC: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/timing_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'PID_controller_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/PID_controller_0.xci
# IP: The module: 'PID_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_4/mult_gen_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_4 || ORIG_REF_NAME==mult_gen_4}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_2/mult_gen_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_2 || ORIG_REF_NAME==mult_gen_2}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_1/mult_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_3/mult_gen_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_3 || ORIG_REF_NAME==mult_gen_3}]

# IP: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/mult_gen_5/mult_gen_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_5 || ORIG_REF_NAME==mult_gen_5}]

# XDC: c:/Users/ahmet/Desktop/test_code/test_code.srcs/sources_1/ip/PID_controller_0/src/timing_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'PID_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
