# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/my/Vivado/PID_Controller/PID_Controller.srcs/sources_1/ip/fixed_to_float/fixed_to_float.xci
# IP: The module: 'fixed_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/PID_Controller/PID_Controller.srcs/sources_1/ip/fixed_to_float/fixed_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed_to_float'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/my/Vivado/PID_Controller/PID_Controller.srcs/sources_1/ip/fixed_to_float/fixed_to_float.xci
# IP: The module: 'fixed_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/PID_Controller/PID_Controller.srcs/sources_1/ip/fixed_to_float/fixed_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed_to_float'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
