# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/accumulator_core/accumulator_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_core || ORIG_REF_NAME==accumulator_core} -quiet] -quiet
