# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/adder_core/adder_core.xci
# IP: The module: 'adder_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/adder_core/adder_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_core'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/adder_core/adder_core.xci
# IP: The module: 'adder_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/adder_core/adder_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
