function compile_hdl_design_top_module
% compile_hdl_design_top_module compiles HDL design
% Generated by Cosimulation Wizard
[s, r] = system(['vsim < hdlverifier_compile_design.do'],'-echo');
if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end

