# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/float_to_fixed/float_to_fixed.xci
# IP: The module: 'float_to_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/float_to_fixed/float_to_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/float_to_fixed/float_to_fixed.xci
# IP: The module: 'float_to_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my/Vivado/pid_controller_v1/pid_controller_v1.srcs/sources_1/ip/float_to_fixed/float_to_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
