# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/90534/Desktop/sum proj/PID_Controller/PID_Controller.srcs/sources_1/ip/adder_core/adder_core.xci
# IP: The module: 'adder_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/90534/Desktop/sum proj/PID_Controller/PID_Controller.srcs/sources_1/ip/adder_core/adder_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_core'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/90534/Desktop/sum proj/PID_Controller/PID_Controller.srcs/sources_1/ip/adder_core/adder_core.xci
# IP: The module: 'adder_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/90534/Desktop/sum proj/PID_Controller/PID_Controller.srcs/sources_1/ip/adder_core/adder_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
